const fs = require('fs');
let c = fs.readFileSync('index.js', 'utf8');

const oldPrompt = `"Extract the following information from the resume text below and return it strictly as a JSON object matching this structure:\\n{\\n  \\"intro\\": { \\"name\\": \\"\\", \\"title\\": \\"\\", \\"summary\\": \\"\\" },\\n  \\"experience\\": [ { \\"id\\": 1, \\"role\\": \\"\\", \\"company\\": \\"\\", \\"years\\": \\"\\", \\"desc\\": \\"\\" } ],\\n  \\"education\\": [ { \\"id\\": 1, \\"degree\\": \\"\\", \\"school\\": \\"\\", \\"years\\": \\"\\", \\"desc\\": \\"\\" } ],\\n  \\"skills\\": [ \\"Skill 1\\", \\"Skill 2\\" ],\\n  \\"projects\\": [ { \\"id\\": 1, \\"title\\": \\"\\", \\"desc\\": \\"\\", \\"tech\\": [\\"Tech 1\\"] } ],\\n  \\"certifications\\": [ { \\"id\\": 1, \\"title\\": \\"\\", \\"issuer\\": \\"\\", \\"year\\": \\"\\" } ],\\n  \\"contact\\": { \\"email\\": \\"\\", \\"linkedin\\": \\"\\", \\"github\\": \\"\\" },\\n  \\"visible\\": {\\n    \\"education\\": true,\\n    \\"skills\\": true,\\n    \\"experience\\": true,\\n    \\"projects\\": true,\\n    \\"certifications\\": true\\n  }\\n}\\n\\nRules:\\n- For the \\"visible\\" object, set the value to false ONLY IF the section is empty or missing in the resume. Otherwise, set it to true.\\n- Extract as accurately as possible. If something is missing, leave it as an empty string or empty array.\\n- EXTREMELY IMPORTANT: Do NOT extract personal or academic projects into the \\"experience\\" array. The \\"experience\\" array is strictly for formal employment or work experience. Projects belong ONLY in the \\"projects\\" array.\\n- DO NOT wrap the output in markdown code blocks like \`\`\`json. Return ONLY the raw JSON string.\\n\\nResume Text:\\n" + text;`;

const newPrompt = `"Extract the following information from the resume text below and return it strictly as a JSON object matching this structure:\\n{\\n  \\"intro\\": { \\"name\\": \\"\\", \\"title\\": \\"\\", \\"summary\\": \\"\\" },\\n  \\"experience\\": [ { \\"id\\": 1, \\"role\\": \\"\\", \\"company\\": \\"\\", \\"years\\": \\"\\", \\"desc\\": \\"\\" } ],\\n  \\"education\\": [ { \\"id\\": 1, \\"degree\\": \\"\\", \\"school\\": \\"\\", \\"years\\": \\"\\", \\"desc\\": \\"\\" } ],\\n  \\"skills\\": [ \\"Skill 1\\", \\"Skill 2\\" ],\\n  \\"categorizedSkills\\": [ { \\"category\\": \\"Category Name\\", \\"items\\": [\\"Skill 1\\", \\"Skill 2\\"] } ],\\n  \\"projects\\": [ { \\"id\\": 1, \\"title\\": \\"\\", \\"desc\\": \\"\\", \\"tech\\": [\\"Tech 1\\"] } ],\\n  \\"certifications\\": [ { \\"id\\": 1, \\"title\\": \\"\\", \\"issuer\\": \\"\\", \\"year\\": \\"\\" } ],\\n  \\"contact\\": { \\"email\\": \\"\\", \\"linkedin\\": \\"\\", \\"github\\": \\"\\" },\\n  \\"visible\\": {\\n    \\"education\\": true,\\n    \\"skills\\": true,\\n    \\"experience\\": true,\\n    \\"projects\\": true,\\n    \\"certifications\\": true\\n  }\\n}\\n\\nRules:\\n- For the \\"visible\\" object, set the value to false ONLY IF the section is empty or missing in the resume. Otherwise, set it to true.\\n- \\"categorizedSkills\\" MUST logically group the extracted skills into exactly 3 or 4 sections with AI-decided category names (e.g., Languages, Frontend, Backend, Tools, etc) based on the candidate's skills.\\n- Extract as accurately as possible. If something is missing, leave it as an empty string or empty array.\\n- EXTREMELY IMPORTANT: Do NOT extract personal or academic projects into the \\"experience\\" array. The \\"experience\\" array is strictly for formal employment or work experience. Projects belong ONLY in the \\"projects\\" array.\\n- DO NOT wrap the output in markdown code blocks like \`\`\`json. Return ONLY the raw JSON string.\\n\\nResume Text:\\n" + text;`;

if (c.includes(oldPrompt)) {
    c = c.replace(oldPrompt, newPrompt);
    fs.writeFileSync('index.js', c);
    console.log("Updated prompt in index.js");
} else {
    console.log("Old prompt not found!");
}
